# Generated by Django 3.1.7 on 2021-03-11 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BooleanFact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('correct_answer', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('key', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('fact_type', models.CharField(choices=[('bool', 'Boolean')], max_length=32)),
                ('boolean_fact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.booleanfact')),
            ],
        ),
    ]
