# Generated by Django 3.1.7 on 2021-03-11 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0003_auto_20210311_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooleanChallenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.booleanfact')),
            ],
        ),
        migrations.CreateModel(
            name='BooleanResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.booleanchallenge')),
            ],
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('challenge_type', models.TextField(choices=[('bool', 'Boolean'), ('numeric', 'Numeric')], max_length=32)),
                ('boolean_challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.booleanchallenge')),
            ],
        ),
        migrations.CreateModel(
            name='NumericChallenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.numericfact')),
            ],
        ),
        migrations.CreateModel(
            name='NumericResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_percent', models.DecimalField(decimal_places=2, max_digits=4)),
                ('ci_low', models.DecimalField(decimal_places=2, max_digits=32)),
                ('ci_high', models.DecimalField(decimal_places=2, max_digits=32)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.numericchallenge')),
            ],
        ),
        migrations.AlterField(
            model_name='fact',
            name='fact_type',
            field=models.TextField(choices=[('bool', 'Boolean'), ('numeric', 'Numeric')], max_length=32),
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('response_type', models.TextField(choices=[('bool', 'Boolean'), ('numeric', 'Numeric')], max_length=32)),
                ('confidence_percent', models.DecimalField(decimal_places=2, max_digits=4)),
                ('correct', models.BooleanField()),
                ('boolean_response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.booleanresponse')),
                ('challenge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quiz.challenge')),
                ('numeric_response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.numericresponse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='challenge',
            name='fact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.fact'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='numeric_challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.numericchallenge'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
