# Generated by Django 3.1.7 on 2021-03-11 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_challenge_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='uid',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
