# Generated by Django 3.1.7 on 2021-03-13 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20210311_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='fact',
            name='version_hash',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
