# Generated by Django 3.1.7 on 2021-03-14 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_fact_version_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('weight', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
            ],
        ),
        migrations.AlterField(
            model_name='numericfact',
            name='correct_answer_unit',
            field=models.CharField(choices=[('none', 'None'), ('g/cm³', 'Grams Per Cc'), ('sq km', 'Square Km'), ('percent', 'Percent')], max_length=32),
        ),
        migrations.AddField(
            model_name='fact',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.factcategory'),
        ),
    ]
