# Generated by Django 3.1.7 on 2021-03-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20210314_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='resolved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='numericfact',
            name='correct_answer_unit',
            field=models.CharField(choices=[('none', 'None'), ('g/cm³', 'Grams Per Cc'), ('sq km', 'Square Km'), ('percent', 'Percent'), ('kelvin', 'Kelvin'), ('celsius', 'Celsius'), ('meters', 'Meters'), ('minutes', 'Minutes'), ('seconds', 'Seconds'), ('grams', 'Grams'), ('kg', 'Kilograms'), ('hours', 'Hours'), ('1E24 kg', 'Kilograms E24'), ('1E6 km', 'Millions Of Km'), ('km', 'Km'), ('km/s', 'Km Per Second'), ('m/s²', 'Meters Per Second Squared')], max_length=32),
        ),
        migrations.CreateModel(
            name='SummaryScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('batch_size', models.IntegerField()),
                ('actual_correct', models.IntegerField()),
                ('expected_correct', models.DecimalField(decimal_places=4, max_digits=8)),
                ('probability_fewer_correct', models.DecimalField(decimal_places=8, max_digits=9)),
                ('probability_same_correct', models.DecimalField(decimal_places=8, max_digits=9)),
                ('probability_more_correct', models.DecimalField(decimal_places=8, max_digits=9)),
                ('datapoints', models.ManyToManyField(related_name='summary_scores', to='quiz.Response')),
            ],
        ),
    ]
