# Generated by Django 3.1.7 on 2021-03-18 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0013_auto_20210317_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('wrong', 'Provided answer is wrong'), ('nonsense', 'Question is incomprehensible'), ('ambiguous', 'Question is ambiguous'), ('typo', 'Bad grammar/spelling'), ('boring', 'Question is not interesting'), ('too-easy', 'Question is too easy'), ('too-hard', 'Question is too hard'), ('other', 'Other')], max_length=32)),
                ('text', models.TextField()),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
