# Generated by Django 3.1.7 on 2021-03-23 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_challengefeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='fact',
            name='fine_print',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='fact',
            name='source',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='fact',
            name='source_link',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
