# Generated by Django 3.1.7 on 2021-03-24 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_auto_20210323_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numericfact',
            name='correct_answer_unit',
            field=models.CharField(choices=[('none', 'None'), ('g/cm³', 'Grams Per Cc'), ('sq km', 'Square Km'), ('percent', 'Percent'), ('kelvin', 'Kelvin'), ('celsius', 'Celsius'), ('meters', 'Meters'), ('minutes', 'Minutes'), ('seconds', 'Seconds'), ('grams', 'Grams'), ('kg', 'Kilograms'), ('hours', 'Hours'), ('1E24 kg', 'Kilograms E24'), ('1E6 km', 'Millions Of Km'), ('km', 'Km'), ('km/s', 'Km Per Second'), ('m/s²', 'Meters Per Second Squared'), ('days', 'Days')], max_length=32),
        ),
    ]
