# Generated by Django 3.1.7 on 2021-03-11 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumericFact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('correct_answer_unit', models.CharField(choices=[('none', 'None'), ('g/cm³', 'Grams Per Cc')], max_length=32)),
                ('correct_answer', models.DecimalField(decimal_places=2, max_digits=32)),
            ],
        ),
        migrations.AlterField(
            model_name='fact',
            name='fact_type',
            field=models.CharField(choices=[('bool', 'Boolean'), ('numeric', 'Numeric')], max_length=32),
        ),
        migrations.AddField(
            model_name='fact',
            name='numeric_fact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.numericfact'),
        ),
    ]
