# Generated by Django 3.1.7 on 2021-03-11 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_challenge_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='booleanresponse',
            name='answer',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booleanresponse',
            name='confidence_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='challenge',
            name='challenge_type',
            field=models.TextField(choices=[('boolean', 'Boolean'), ('numeric', 'Numeric')], max_length=32),
        ),
        migrations.AlterField(
            model_name='fact',
            name='fact_type',
            field=models.TextField(choices=[('boolean', 'Boolean'), ('numeric', 'Numeric')], max_length=32),
        ),
        migrations.AlterField(
            model_name='response',
            name='response_type',
            field=models.TextField(choices=[('boolean', 'Boolean'), ('numeric', 'Numeric')], max_length=32),
        ),
    ]
